name: build-test-deploy
on: push
jobs:
  build:
    runs-on: mhub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          submodules: recursive
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22.0
      - run: go install -C Backend
      - run: go build -C Backend