name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22.0
      - run: go install
      - run: go build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22.0
      - run: go install
      - run: go test ./...
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22.0
      - run: echo "Deployment not implemented"